# lint 체크 비활성화 파일
# swiftLint
# https://realm.github.io/SwiftLint/rule-directory.html

# 비활성화 파일 목록 경로를 지정합니다.
excluded:
  - Sources/AppDelegate.swift

# 활성화 룰
opt_in_rules:
  - empty_count
  - force_unwrapping
  - required_enum_case
  - identifier_name
  - colon
  - sorted_imports
  - comma
  - force_try # try! 대신 do catch를 사용해 앱 안정성에 신경써야합니다. default: error

# 라인의 최대 글자수를 지정합니다.
# 80자 이상의 경우 경고, 100자 이상일 경우 에러를 나타냅니다.
line_length:
  - 80
  - 100

# 강제 언랩핑 에러 출력
force_unwrapping:
  severity: error

# colon 에러 출력
colon:
  severity: error

# 잘못된 comma 위치 에러 출력
comma:
  severity: error

# import 정렬과 관련해, 오름차순 정렬
# 줄바꿈의 경우 무시되기 때문에, FirstParty, ThirdParty 구분은 가능
sorted_imports:
  severity: error


