# lint 체크 비활성화 파일
# swiftLint
# https://realm.github.io/SwiftLint/rule-directory.html

# 비활성화 파일 목록 경로를 지정합니다.
excluded:
  - Sources/AppDelegate.swift
  - DemoApp/Sources/LoginAppDelegate.swift

# 비활성화 룰
disabled_rules:
  - trailing_whitespace # line의 마지막에는 빈 여백이 있으면 안됩니다. https://realm.github.io/SwiftLint/trailing_whitespace.html
  - identifier_name # 변수나 클래스등 이름은 소문자, 대문자로 시작하며 너무길거나 짧으면 안됩니다. https://realm.github.io/SwiftLint/identifier_name.html

# 활성화 룰
opt_in_rules:
  - empty_count # count > 0 대신 isEmpty사용 https://realm.github.io/SwiftLint/empty_count.html
  - empty_string # string 빈문자열 체크시 "" 대신 isempty를 사용한다 https://realm.github.io/SwiftLint/empty_string.html
  - force_unwrapping # force unwrapping을 하지 않습니다. https://realm.github.io/SwiftLint/force_unwrapping.html
  - colon #colon 사용시 앞에는 여백이 없고 뒤에는 공백이 있어야합니다. https://realm.github.io/SwiftLint/colon.html
  - sorted_imports # import 들의 라인 인덴트들이 일치해야 합니다. https://realm.github.io/SwiftLint/sorted_imports.html
  - comma #comma 앞에는 여백이 없고 뒤에는 공백이 있어야합니다. https://realm.github.io/SwiftLint/comma.html
  - force_try # try! 대신 do catch를 사용해 앱 안정성에 신경써야합니다. default: error
  - closure_spacing # 클로저의 내용과 괄호사이엔 공백이 있어야합니다 https://realm.github.io/SwiftLint/closure_spacing.html
  - duplicate_imports # 중복 import 방지 https://realm.github.io/SwiftLint/duplicate_imports.html
  - unused_import # 사용하지 않는 import는 제거 합니다. https://realm.github.io/SwiftLint/unused_import.html
  - multiline_parameters # 파라미터들도 한줄에 있거나 따로 있어야 합니다. https://realm.github.io/SwiftLint/multiline_parameters.html
  - return_arrow_whitespace # return 화살표에는 양옆으로 공백이 있어야 합니다. https://realm.github.io/SwiftLint/return_arrow_whitespace.html
  - vertical_whitespace # 수직으로는 여백이 2줄이상 생기면 안됩니다. https://realm.github.io/SwiftLint/vertical_whitespace.html
  - void_return #  -> () 보단 -> Void 를 선호합니다.
  
# 라인의 최대 글자수를 지정합니다.
# 80자 이상의 경우 경고, 100자 이상일 경우 에러를 나타냅니다.
line_length:
  - 80
  - 100

# 강제 언랩핑 에러 출력
force_unwrapping:
  severity: error

# colon 에러 출력
colon:
  severity: error

# 잘못된 comma 위치 에러 출력
comma:
  severity: error

# import 정렬과 관련해, 오름차순 정렬
# 줄바꿈의 경우 무시되기 때문에, FirstParty, ThirdParty 구분은 가능
sorted_imports:
  severity: error


